/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StarterKitRouteImport } from './routes/starter-kit'
import { Route as ToolMatchRouteImport } from './routes/tool-match'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as GuidesHvacAutomationRouteImport } from './routes/guides/hvac-automation'
import { Route as GuidesLeadFollowUpSequenceRouteImport } from './routes/guides/lead-follow-up-sequence'
import { Route as GuidesMissedCallTextBackRouteImport } from './routes/guides/missed-call-text-back'
import { Route as GuidesPlumbingAutomationRouteImport } from './routes/guides/plumbing-automation'
import { Route as GuidesRoofingAutomationRouteImport } from './routes/guides/roofing-automation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StarterKitRoute = StarterKitRouteImport.update({
  id: '/starter-kit',
  path: '/starter-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolMatchRoute = ToolMatchRouteImport.update({
  id: '/tool-match',
  path: '/tool-match',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesHvacAutomationRoute = GuidesHvacAutomationRouteImport.update({
  id: '/guides/hvac-automation',
  path: '/guides/hvac-automation',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesLeadFollowUpSequenceRoute =
  GuidesLeadFollowUpSequenceRouteImport.update({
    id: '/guides/lead-follow-up-sequence',
    path: '/guides/lead-follow-up-sequence',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesMissedCallTextBackRoute =
  GuidesMissedCallTextBackRouteImport.update({
    id: '/guides/missed-call-text-back',
    path: '/guides/missed-call-text-back',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesPlumbingAutomationRoute =
  GuidesPlumbingAutomationRouteImport.update({
    id: '/guides/plumbing-automation',
    path: '/guides/plumbing-automation',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesRoofingAutomationRoute = GuidesRoofingAutomationRouteImport.update({
  id: '/guides/roofing-automation',
  path: '/guides/roofing-automation',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/starter-kit': typeof StarterKitRoute
  '/tool-match': typeof ToolMatchRoute
  '/guides/hvac-automation': typeof GuidesHvacAutomationRoute
  '/guides/lead-follow-up-sequence': typeof GuidesLeadFollowUpSequenceRoute
  '/guides/missed-call-text-back': typeof GuidesMissedCallTextBackRoute
  '/guides/plumbing-automation': typeof GuidesPlumbingAutomationRoute
  '/guides/roofing-automation': typeof GuidesRoofingAutomationRoute
  '/guides/': typeof GuidesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/starter-kit': typeof StarterKitRoute
  '/tool-match': typeof ToolMatchRoute
  '/guides/hvac-automation': typeof GuidesHvacAutomationRoute
  '/guides/lead-follow-up-sequence': typeof GuidesLeadFollowUpSequenceRoute
  '/guides/missed-call-text-back': typeof GuidesMissedCallTextBackRoute
  '/guides/plumbing-automation': typeof GuidesPlumbingAutomationRoute
  '/guides/roofing-automation': typeof GuidesRoofingAutomationRoute
  '/guides': typeof GuidesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/starter-kit': typeof StarterKitRoute
  '/tool-match': typeof ToolMatchRoute
  '/guides/hvac-automation': typeof GuidesHvacAutomationRoute
  '/guides/lead-follow-up-sequence': typeof GuidesLeadFollowUpSequenceRoute
  '/guides/missed-call-text-back': typeof GuidesMissedCallTextBackRoute
  '/guides/plumbing-automation': typeof GuidesPlumbingAutomationRoute
  '/guides/roofing-automation': typeof GuidesRoofingAutomationRoute
  '/guides/': typeof GuidesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/starter-kit'
    | '/tool-match'
    | '/guides/hvac-automation'
    | '/guides/lead-follow-up-sequence'
    | '/guides/missed-call-text-back'
    | '/guides/plumbing-automation'
    | '/guides/roofing-automation'
    | '/guides/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/starter-kit'
    | '/tool-match'
    | '/guides/hvac-automation'
    | '/guides/lead-follow-up-sequence'
    | '/guides/missed-call-text-back'
    | '/guides/plumbing-automation'
    | '/guides/roofing-automation'
    | '/guides'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/starter-kit'
    | '/tool-match'
    | '/guides/hvac-automation'
    | '/guides/lead-follow-up-sequence'
    | '/guides/missed-call-text-back'
    | '/guides/plumbing-automation'
    | '/guides/roofing-automation'
    | '/guides/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StarterKitRoute: typeof StarterKitRoute
  ToolMatchRoute: typeof ToolMatchRoute
  GuidesHvacAutomationRoute: typeof GuidesHvacAutomationRoute
  GuidesLeadFollowUpSequenceRoute: typeof GuidesLeadFollowUpSequenceRoute
  GuidesMissedCallTextBackRoute: typeof GuidesMissedCallTextBackRoute
  GuidesPlumbingAutomationRoute: typeof GuidesPlumbingAutomationRoute
  GuidesRoofingAutomationRoute: typeof GuidesRoofingAutomationRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/starter-kit': {
      id: '/starter-kit'
      path: '/starter-kit'
      fullPath: '/starter-kit'
      preLoaderRoute: typeof StarterKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool-match': {
      id: '/tool-match'
      path: '/tool-match'
      fullPath: '/tool-match'
      preLoaderRoute: typeof ToolMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/hvac-automation': {
      id: '/guides/hvac-automation'
      path: '/guides/hvac-automation'
      fullPath: '/guides/hvac-automation'
      preLoaderRoute: typeof GuidesHvacAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/lead-follow-up-sequence': {
      id: '/guides/lead-follow-up-sequence'
      path: '/guides/lead-follow-up-sequence'
      fullPath: '/guides/lead-follow-up-sequence'
      preLoaderRoute: typeof GuidesLeadFollowUpSequenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/missed-call-text-back': {
      id: '/guides/missed-call-text-back'
      path: '/guides/missed-call-text-back'
      fullPath: '/guides/missed-call-text-back'
      preLoaderRoute: typeof GuidesMissedCallTextBackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/plumbing-automation': {
      id: '/guides/plumbing-automation'
      path: '/guides/plumbing-automation'
      fullPath: '/guides/plumbing-automation'
      preLoaderRoute: typeof GuidesPlumbingAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/roofing-automation': {
      id: '/guides/roofing-automation'
      path: '/guides/roofing-automation'
      fullPath: '/guides/roofing-automation'
      preLoaderRoute: typeof GuidesRoofingAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StarterKitRoute: StarterKitRoute,
  ToolMatchRoute: ToolMatchRoute,
  GuidesHvacAutomationRoute: GuidesHvacAutomationRoute,
  GuidesLeadFollowUpSequenceRoute: GuidesLeadFollowUpSequenceRoute,
  GuidesMissedCallTextBackRoute: GuidesMissedCallTextBackRoute,
  GuidesPlumbingAutomationRoute: GuidesPlumbingAutomationRoute,
  GuidesRoofingAutomationRoute: GuidesRoofingAutomationRoute,
  GuidesIndexRoute: GuidesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}